from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(template_name="projects/login.html"), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
    path("accounts/profile/", views.profile, name="profile"),
    path("accounts/register/", views.register, name="register"),
    path("admin-tools/", views.admin_tools, name="admin-tools"),
    path("", views.ProjectListView.as_view(), name="project-list"),
    path("content/", views.content_list, name="content-list"),
    path("content/<int:pk>/", views.content_detail, name="content-detail"),
    path("communities/", views.community_home, name="community-home"),
    path("communities/<int:community_id>/member/", views.community_member_home, name="community-member-home"),
    path(
        "communities/<int:community_id>/member/projects/<int:project_id>/judge/",
        views.community_member_judge_project,
        name="community-member-judge-project",
    ),
    path("communities/<int:community_id>/organiser/", views.community_organiser_home, name="community-organiser-home"),
    path(
        "communities/<int:community_id>/organiser/projects/<int:project_id>/review/",
        views.community_organiser_review_project,
        name="community-organiser-review-project",
    ),
    path("projects/new/", views.ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/", views.ProjectDetailView.as_view(), name="project-detail"),
    path("projects/<int:pk>/annotation/", views.ProjectAnnotationView.as_view(), name="project-annotation-home"),
    path(
        "projects/<int:pk>/annotation/manual/top-level/",
        views.manual_top_level,
        name="manual-top-level",
    ),
    path(
        "projects/<int:pk>/annotation/manual/segmentation-phase-1/",
        views.manual_segmentation_phase_1,
        name="manual-segmentation-phase-1",
    ),
    path(
        "projects/<int:pk>/annotation/manual/segmentation-phase-2/",
        views.manual_segmentation_phase_2,
        name="manual-segmentation-phase-2",
    ),
    path(
        "projects/<int:pk>/annotation/manual/translation/",
        views.manual_translation,
        name="manual-translation",
    ),
    path(
        "projects/<int:pk>/annotation/manual/page-oriented/",
        views.manual_page_annotation,
        name="manual-page-annotation",
    ),
    path(
        "projects/<int:pk>/annotation/manual/mwe/",
        views.manual_mwe,
        name="manual-mwe",
    ),
    path(
        "projects/<int:pk>/annotation/manual/lemma/",
        views.manual_lemma,
        name="manual-lemma",
    ),
    path(
        "projects/<int:pk>/annotation/manual/gloss/",
        views.manual_gloss,
        name="manual-gloss",
    ),
    path(
        "projects/<int:pk>/annotation/manual/pinyin/",
        views.manual_pinyin,
        name="manual-pinyin",
    ),
    path("projects/<int:pk>/images/", views.project_images_home, name="project-images-home"),
    path("projects/<int:pk>/exercises/", views.project_exercises_home, name="project-exercises-home"),
    path("projects/<int:pk>/images/style/", views.project_image_style, name="project-image-style"),
    path("projects/<int:pk>/images/elements/", views.project_image_elements, name="project-image-elements"),
    path("projects/<int:pk>/images/pages/", views.project_image_pages, name="project-image-pages"),
    path("projects/<int:pk>/image-placement/", views.set_page_image_placement, name="project-image-placement"),
    path("projects/<int:pk>/processing-options/", views.set_processing_options, name="project-processing-options"),
    path("projects/<int:pk>/exercises/cloze/", views.generate_cloze_exercises, name="project-generate-cloze"),
    path("projects/<int:pk>/exercises/flashcards/", views.generate_flashcard_exercises, name="project-generate-flashcards"),
    path("exercise-sets/<int:set_id>/", views.exercise_set_detail, name="exercise-set-detail"),
    path("exercise-sets/<int:set_id>/play/", views.exercise_set_play, name="exercise-set-play"),
    path("exercise-sets/<int:set_id>/publish/", views.publish_exercise_set, name="exercise-set-publish"),
    path("content/<int:pk>/exercises/", views.published_exercises_for_project, name="content-exercises"),
    path("projects/<int:pk>/collaborators/", views.set_project_collaborator, name="project-collaborators"),
    path("projects/<int:pk>/community/", views.set_project_community, name="project-community"),
    path("projects/<int:pk>/compile/", views.compile_project, name="project-compile"),
    path(
        "projects/<int:pk>/compile/monitor/<uuid:report_id>/",
        views.compile_monitor,
        name="project-compile-monitor",
    ),
    path(
        "projects/<int:pk>/compile/status/<uuid:report_id>/",
        views.compile_status,
        name="project-compile-status",
    ),
    path("projects/<int:pk>/download-bundle/", views.download_project_bundle, name="project-download-bundle"),
    path(
        "projects/<int:pk>/download-source-bundle/",
        views.download_project_source_bundle,
        name="project-download-source-bundle",
    ),
    path("projects/import-source-bundle/", views.import_project_source_bundle, name="project-import-source-bundle"),
    path("projects/<int:pk>/publish/", views.toggle_publish, name="project-publish"),
    path("projects/<int:pk>/discovery-metadata/", views.set_project_discovery_metadata, name="project-discovery-metadata"),
    path("projects/<int:pk>/target-language/", views.set_project_target_language, name="project-target-language"),
    path("projects/<int:pk>/clone/", views.clone_project, name="project-clone"),
    path("projects/<int:pk>/delete/", views.delete_project, name="project-delete"),
    path("projects/<int:pk>/compiled/<path:path>", views.serve_compiled, name="project-compiled"),
]
