# Generated by Django 5.2.17 on 2026-09-28 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='photo_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PhotoStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('processing', 'processing'), ('candidate', 'candidate'), ('unclear', 'unclear'), ('failed', 'failed'), ('confirmed', 'confirmed'), ('saved', 'saved'), ('discarded', 'discarded')], default='processing', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=80)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(max_length=80)),
                ('explanation_language', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('personal_key', models.BooleanField(default=False)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_dictionary.dictionary')),
                ('saved_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_dictionary.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
