# Generated by Django 5.2.17 on 2026-09-28 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0002_photo_learning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='tts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photostudy',
            name='source_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.entry'),
        ),
        migrations.AddField(
            model_name='photostudy',
            name='source_image_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photostudy',
            name='source_text_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AudioStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed'), ('saved', 'saved'), ('discarded', 'discarded')], default='processing', max_length=16)),
                ('source_text', models.CharField(max_length=255)),
                ('source_text_version', models.PositiveIntegerField()),
                ('source_text_id', models.PositiveBigIntegerField()),
                ('language', models.CharField(max_length=80)),
                ('language_code', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=80)),
                ('voice', models.CharField(max_length=40)),
                ('personal_key', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(default='audio/wav', max_length=80)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_dictionary.dictionary')),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_dictionary.entry')),
                ('saved_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_dictionary.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
