# Generated by Django 5.2.17 on 2026-09-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0003_entry_photo_and_saved_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='photo_ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='tts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(choices=[('marin', 'Marin'), ('cedar', 'Cedar'), ('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('nova', 'Nova'), ('onyx', 'Onyx'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='marin', max_length=40)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_dictionary.dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'dictionary'), name='cd_unique_voice_preference')],
            },
        ),
    ]
