# Generated by Django 5.2.17 on 2026-09-30 23:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0004_ai_defaults_and_voices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_links', to='community_dictionary.contribution')),
                ('word_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_links', to='community_dictionary.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image', 'word_entry'), name='cd_unique_image_word')],
            },
        ),
    ]
