# Generated by Django 5.2.17 on 2026-10-01 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0005_image_word_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('value', models.CharField(blank=True, max_length=16)),
                ('base_revision', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='controlled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_dictionary_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='previous_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_revisions', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_copies', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='text_field',
            field=models.CharField(blank=True, choices=[('word', 'Word or phrase'), ('meaning', 'Translation or explanation'), ('category', 'Category')], max_length=10),
        ),
        migrations.AddField(
            model_name='contribution',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='withdrawn_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_contributions', to='community_dictionary.entry'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='collection_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_collections', to='community_dictionary.dictionary'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='membership_policy',
            field=models.CharField(choices=[('owner', 'Owner manages membership'), ('coordinators', 'Two coordinators approve changes')], default='owner', max_length=16),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='membership_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='category_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='collection_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_entries', to='community_dictionary.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='current_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='entry',
            name='current_meaning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='entry',
            name='meaning_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('inactive', 'Inactive')], default='invited', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('editor', 'Editor'), ('coordinator', 'Coordinator')], default='member', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='dictionary',
            constraint=models.UniqueConstraint(condition=models.Q(('personal', True)), fields=('owner', 'collection_source'), name='cd_personal_collection'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('collection_source__isnull', False)), fields=('dictionary', 'collection_source'), name='cd_collection_entry'),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_decisions', to='community_dictionary.dictionary'),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community_dictionary.membership'),
        ),
        migrations.AddField(
            model_name='membershipdecision',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
