# Generated by Django 5.2.17 on 2026-10-02 23:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0009_restore_experimental_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='image_generation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='image_generation_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='image_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.contribution'),
        ),
        migrations.CreateModel(
            name='ImageStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('style', 'Style sample'), ('entry', 'Entry picture')], max_length=8)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed'), ('saved', 'saved'), ('discarded', 'discarded')], default='processing', max_length=16)),
                ('subject', models.CharField(max_length=2000)),
                ('style_description', models.CharField(max_length=2000)),
                ('style_baseline_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('participation_revision', models.PositiveIntegerField(default=0)),
                ('membership_revision', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('policy_revision', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(max_length=80)),
                ('quality', models.CharField(default='high', max_length=16)),
                ('personal_key', models.BooleanField(default=False)),
                ('usage', models.JSONField(default=dict)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('accounted', models.BooleanField(default=False)),
                ('failure_code', models.CharField(blank=True, max_length=40)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_dictionary.dictionary')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_dictionary.entry')),
                ('saved_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.contribution')),
                ('source_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
