# Generated by Django 5.2.17 on 2026-10-04 02:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0010_image_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('language', models.CharField(max_length=80)),
                ('explanation_language', models.CharField(max_length=80)),
                ('voice', models.CharField(choices=[('marin', 'Marin'), ('cedar', 'Cedar'), ('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('nova', 'Nova'), ('onyx', 'Onyx'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='marin', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_port', to='community_dictionary.dictionary')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='language_ports', to='community_dictionary.dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='estimate', max_length=16)),
                ('source_language', models.CharField(max_length=80)),
                ('source_explanation_language', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('prices', models.JSONField(default=dict)),
                ('payer', models.CharField(max_length=8)),
                ('estimated_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('allowance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('reserved_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('charged_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('settled', models.BooleanField(default=False)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('protected', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('queue_error', models.BooleanField(default=False)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='community_dictionary.languageport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_dependencies', to='community_dictionary.contribution')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_uses', to='community_dictionary.contribution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'derived'), name='cd_unique_dependency')],
            },
        ),
        migrations.CreateModel(
            name='PortEntryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_digest', models.CharField(max_length=64)),
                ('manually_edited', models.BooleanField(default=False)),
                ('destination_digest', models.CharField(max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.entry')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_links', to='community_dictionary.languageport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.entry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('port', 'source'), name='cd_unique_port_entry')],
            },
        ),
        migrations.CreateModel(
            name='PortItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('destination_digest', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='waiting', max_length=16)),
                ('phase', models.CharField(blank=True, max_length=16)),
                ('result', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('usage', models.JSONField(default=dict)),
                ('translation_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('audio_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('estimated_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('allowance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('uncertain_cost', models.BooleanField(default=False)),
                ('invalidated', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('source_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.entry')),
                ('sources', models.ManyToManyField(related_name='port_previews', to='community_dictionary.contribution')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='community_dictionary.portrun')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('run', 'source_entry'), name='cd_unique_port_item')],
            },
        ),
    ]
