# Generated by Django 5.2.17 on 2026-10-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0011_languageport_portrun_contributiondependency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrun',
            name='category_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
