# Generated by Django 5.2.17 on 2026-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0012_port_category_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiostudy',
            name='source_meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audiostudy',
            name='source_meaning_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiostudy',
            name='synthesis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
