# Generated by Django 5.2.17 on 2026-10-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0013_tts_pronunciation_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='portitem',
            name='attention_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portitem',
            name='needs_attention',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='portitem',
            name='review_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
