# Generated by Django 5.2.17 on 2026-10-07 03:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0014_port_review_attention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewordlink', name='sentence_text',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='capture_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='sentence_capture_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('word', 'Word'), ('sentence', 'Sentence')], default='word', max_length=12),
        ),
        migrations.CreateModel(
            name='AttentionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_reports', to='community_dictionary.entry')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community_dictionary.contribution')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_checks', to='community_dictionary.entry')),
                ('meaning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community_dictionary.contribution')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community_dictionary.contribution')),
            ],
        ),
        migrations.CreateModel(
            name='PictureCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='waiting', max_length=12)),
                ('language', models.CharField(max_length=80)),
                ('explanation_language', models.CharField(max_length=80)),
                ('input_language', models.CharField(max_length=80)),
                ('input_mode', models.CharField(default='text', max_length=8)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('recording_path', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(max_length=80)),
                ('personal_key', models.BooleanField(default=False)),
                ('voice', models.CharField(default='marin', max_length=40)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('membership_revision', models.PositiveIntegerField(default=0)),
                ('participation_revision', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_dictionary.dictionary')),
                ('saved_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.entry')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.contribution')),
                ('sources', models.ManyToManyField(related_name='+', to='community_dictionary.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaptureSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('status', models.CharField(default='waiting', max_length=12)),
                ('text', models.CharField(max_length=255)),
                ('meaning', models.CharField(blank=True, max_length=1000)),
                ('language', models.CharField(max_length=80)),
                ('text_id', models.PositiveBigIntegerField(null=True)),
                ('meaning_id', models.PositiveBigIntegerField(null=True)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('report', models.JSONField(default=dict)),
                ('contribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='community_dictionary.contribution')),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='community_dictionary.entry')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='community_dictionary.picturecapture')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(max_length=100)),
                ('sentence_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_words', to='community_dictionary.contribution')),
                ('word_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_uses', to='community_dictionary.entry')),
                ('word_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.contribution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sentence_text', 'word_entry'), name='cd_sentence_word_unique')],
            },
        ),
    ]
