# Generated by Django 5.2.17 on 2026-10-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0015_picture_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='capture_daily_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
