# Generated by Django 5.2.17 on 2026-10-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0016_capture_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
