# Generated by Django 5.2.17 on 2026-10-09 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0017_dictionary_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portrun',
            name='stage',
            field=models.CharField(default='legacy', max_length=16),
        ),
        migrations.CreateModel(
            name='VocabularyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('words', models.JSONField(default=list)),
                ('recipe', models.CharField(max_length=80)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_state', to='community_dictionary.entry')),
            ],
        ),
        migrations.CreateModel(
            name='PortSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='waiting', max_length=16)),
                ('started_at', models.DateTimeField(null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('report', models.JSONField(default=dict)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.entry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='community_dictionary.portitem')),
                ('meaning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.contribution')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='community_dictionary.portrun')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='community_dictionary.contribution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'entry', 'text'), name='cd_port_shared_speech')],
            },
        ),
    ]
