# Generated by Django 5.2.17 on 2026-10-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_dictionary', '0018_port_vocabulary_stages'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portitem',
            name='cd_unique_port_item',
        ),
        migrations.AddField(
            model_name='languageport',
            name='is_description_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portitem',
            name='saved_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='description_jobs', to='community_dictionary.entry'),
        ),
        migrations.AddField(
            model_name='portitem',
            name='source_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='description_items', to='community_dictionary.contribution'),
        ),
        migrations.AddField(
            model_name='portrun',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='portitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_image__isnull', True)), fields=('run', 'source_entry'), name='cd_unique_port_item'),
        ),
        migrations.AddConstraint(
            model_name='portitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_image__isnull', False)), fields=('run', 'source_image'), name='cd_unique_image_job'),
        ),
    ]
