# Generated by Django 5.2.8 on 2025-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="input_mode",
            field=models.CharField(
                choices=[
                    ("description", "Description (AI-generate text)"),
                    ("source_text", "Source text"),
                ],
                default="source_text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="source_text",
            field=models.TextField(blank=True),
        ),
    ]
