# Generated by Django 5.2.12 on 2026-04-05 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_input_mode_alter_project_source_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualStageState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("segmentation", "Segmentation"),
                            ("translation", "Translation"),
                            ("mwe", "MWE"),
                            ("lemma", "Lemma"),
                            ("gloss", "Gloss"),
                            ("audio", "Audio"),
                            ("romanization", "Pinyin/Romanization"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("ready_for_review", "Ready for review"),
                            ("approved", "Approved"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("approved_version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_stage_states",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "stage"],
                "unique_together": {("project", "stage")},
            },
        ),
        migrations.CreateModel(
            name="SegmentationManualVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("source_text_snapshot", models.TextField(blank=True, default="")),
                ("page_breaks", models.JSONField(blank=True, default=list)),
                ("segment_breaks", models.JSONField(blank=True, default=list)),
                ("token_breaks", models.JSONField(blank=True, default=list)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_versions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "-version"],
                "unique_together": {("project", "version")},
            },
        ),
    ]
