# Generated by Django 5.2.12 on 2026-04-05 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    profile_model = apps.get_model("projects", "Profile")
    for user in user_model.objects.all().iterator():
        profile_model.objects.get_or_create(user=user, defaults={"timezone": "UTC"})


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_manualstagestate_segmentationmanualversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
            },
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
