# Generated by Django 5.2.12 on 2026-04-05 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    profile_model = apps.get_model("projects", "Profile")
    for user in user_model.objects.all().iterator():
        profile_model.objects.get_or_create(user=user, defaults={"timezone": "UTC"})


def create_profile_table_if_missing(apps, schema_editor):
    profile_model = apps.get_model("projects", "Profile")
    table_names = schema_editor.connection.introspection.table_names()
    if "projects_profile" not in table_names:
        schema_editor.create_model(profile_model)
        return

    # If the table already exists (from older branch history), make sure its
    # columns match the current migration state before any ORM query runs.
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, "projects_profile")
        }

    for field in profile_model._meta.local_fields:
        if field.column not in existing_columns:
            schema_editor.add_field(profile_model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_manualstagestate_segmentationmanualversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Profile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("timezone", models.CharField(default="UTC", max_length=64)),
                        (
                            "display_name",
                            models.CharField(blank=True, default="", max_length=120),
                        ),
                        ("bio", models.TextField(blank=True, default="")),
                        ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "user",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="profile",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["user_id"],
                    },
                )
            ],
            database_operations=[
                migrations.RunPython(create_profile_table_if_missing, migrations.RunPython.noop),
            ],
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
