# Generated by Django 5.2.12 on 2026-04-05 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def ensure_models_for_0005(apps, schema_editor):
    model_names = [
        "ExerciseSet",
        "ExerciseItem",
        "ProjectImageStyle",
        "TaskUpdate",
        "ProjectCollaborator",
        "ProjectImageElement",
        "ProjectImagePage",
    ]
    table_names = set(schema_editor.connection.introspection.table_names())
    for model_name in model_names:
        model = apps.get_model("projects", model_name)
        table = model._meta.db_table
        if table not in table_names:
            schema_editor.create_model(model)
            table_names.add(table)
            continue

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(cursor, table)
            }
        for field in model._meta.local_fields:
            if field.column not in existing_columns:
                schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("exercise_type", models.CharField(default="cloze", max_length=30)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("distractors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.exerciseset",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise_set_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImageStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brief_description", models.TextField(blank=True, default="")),
                ("expanded_prompt", models.TextField(blank=True, default="")),
                (
                    "sample_image_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_style",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("level", models.CharField(default="info", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_updates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("annotator", "Annotator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "user_id"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectImageElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element_key", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "canonical_image_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_elements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "element_key"],
                "unique_together": {("project", "element_key")},
            },
        ),
        migrations.CreateModel(
            name="ProjectImagePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_index", models.PositiveIntegerField(default=1)),
                ("prompt", models.TextField(blank=True, default="")),
                (
                    "image_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_pages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "page_index"],
                "unique_together": {("project", "page_index")},
            },
        ),
            ],
            database_operations=[
                migrations.RunPython(ensure_models_for_0005, migrations.RunPython.noop),
            ],
        ),
    ]
