# Generated by Django 5.2.12 on 2026-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_exerciseset_exerciseitem_projectimagestyle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimagestyle",
            name="ai_model",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="projectimagestyle",
            name="expanded_style_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimagestyle",
            name="sample_image_model",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="projectimagestyle",
            name="sample_image_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimagestyle",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="projectimagestyle",
            name="style_brief",
            field=models.TextField(blank=True, default=""),
        ),
    ]
