# Generated by Django 5.2.12 on 2026-04-05 08:30

from django.db import migrations, models


def ensure_fields_for_0006(apps, schema_editor):
    model = apps.get_model("projects", "ProjectImageStyle")
    table = model._meta.db_table
    table_names = set(schema_editor.connection.introspection.table_names())
    if table not in table_names:
        schema_editor.create_model(model)
        return
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }
    column_sql = {
        "ai_model": "VARCHAR(120) NOT NULL DEFAULT ''",
        "expanded_style_description": "TEXT NOT NULL DEFAULT ''",
        "sample_image_model": "VARCHAR(120) NOT NULL DEFAULT ''",
        "sample_image_prompt": "TEXT NOT NULL DEFAULT ''",
        "status": "VARCHAR(40) NOT NULL DEFAULT ''",
        "style_brief": "TEXT NOT NULL DEFAULT ''",
    }
    qn = schema_editor.quote_name
    for column, sql_type in column_sql.items():
        if column not in existing_columns:
            schema_editor.execute(f"ALTER TABLE {qn(table)} ADD COLUMN {qn(column)} {sql_type}")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_exerciseset_exerciseitem_projectimagestyle_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="ai_model",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="expanded_style_description",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="sample_image_model",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="sample_image_prompt",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="status",
                    field=models.CharField(blank=True, default="", max_length=40),
                ),
                migrations.AddField(
                    model_name="projectimagestyle",
                    name="style_brief",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_fields_for_0006, migrations.RunPython.noop),
            ],
        ),
    ]
