# Generated by Django 5.2.12 on 2026-04-05 09:01

from django.db import migrations, models


def ensure_fields_for_0007(apps, schema_editor):
    model = apps.get_model("projects", "ProjectImageElement")
    table = model._meta.db_table
    table_names = set(schema_editor.connection.introspection.table_names())
    if table not in table_names:
        schema_editor.create_model(model)
        return
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }
    for field_name in (
        "element_type",
        "expanded_description",
        "expanded_prompt",
        "image_model",
        "image_revised_prompt",
        "is_confirmed",
        "name",
        "page_refs",
        "why_consistency_matters",
    ):
        field = model._meta.get_field(field_name)
        if field.column not in existing_columns:
            schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectimagestyle_ai_model_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="projectimageelement",
                    name="element_type",
                    field=models.CharField(blank=True, default="", max_length=80),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="expanded_description",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="expanded_prompt",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="image_model",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="image_revised_prompt",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="is_confirmed",
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="name",
                    field=models.CharField(blank=True, default="", max_length=200),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="page_refs",
                    field=models.CharField(blank=True, default="", max_length=200),
                ),
                migrations.AddField(
                    model_name="projectimageelement",
                    name="why_consistency_matters",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_fields_for_0007, migrations.RunPython.noop),
            ],
        ),
    ]
