# Generated by Django 5.2.12 on 2026-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectimagestyle_ai_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimageelement",
            name="element_type",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="expanded_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="expanded_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="image_model",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="image_revised_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="page_refs",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="projectimageelement",
            name="why_consistency_matters",
            field=models.TextField(blank=True, default=""),
        ),
    ]
