# Generated by Django 5.2.12 on 2026-04-05 09:22

from django.db import migrations, models


def ensure_fields_for_0008(apps, schema_editor):
    model = apps.get_model("projects", "ProjectImagePage")
    table = model._meta.db_table
    table_names = set(schema_editor.connection.introspection.table_names())
    if table not in table_names:
        schema_editor.create_model(model)
        return
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }
    column_sql = {
        "generation_prompt": "TEXT NOT NULL DEFAULT ''",
        "image_model": "VARCHAR(120) NOT NULL DEFAULT ''",
        "image_revised_prompt": "TEXT NOT NULL DEFAULT ''",
        "page_number": "INTEGER NOT NULL DEFAULT 1",
        "page_text": "TEXT NOT NULL DEFAULT ''",
        "status": "VARCHAR(40) NOT NULL DEFAULT ''",
    }
    qn = schema_editor.quote_name
    for column, sql_type in column_sql.items():
        if column not in existing_columns:
            schema_editor.execute(f"ALTER TABLE {qn(table)} ADD COLUMN {qn(column)} {sql_type}")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectimageelement_element_type_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="projectimagepage",
                    name="generation_prompt",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimagepage",
                    name="image_model",
                    field=models.CharField(blank=True, default="", max_length=120),
                ),
                migrations.AddField(
                    model_name="projectimagepage",
                    name="image_revised_prompt",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimagepage",
                    name="page_number",
                    field=models.PositiveIntegerField(default=1),
                ),
                migrations.AddField(
                    model_name="projectimagepage",
                    name="page_text",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="projectimagepage",
                    name="status",
                    field=models.CharField(blank=True, default="", max_length=40),
                ),
            ],
            database_operations=[
                migrations.RunPython(ensure_fields_for_0008, migrations.RunPython.noop),
            ],
        ),
    ]
