# Generated by Django 5.2.12 on 2026-04-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectimageelement_element_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimagepage",
            name="generation_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="image_model",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="image_revised_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="page_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="page_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="status",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
