# Generated by Django 5.2.12 on 2026-03-25 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_projectimageelement_image_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImagePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("page_text", models.TextField(blank=True)),
                ("generation_prompt", models.TextField(blank=True)),
                ("image_model", models.CharField(default="gpt-image-1", max_length=64)),
                ("image_path", models.CharField(blank=True, max_length=512)),
                ("image_revised_prompt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_pages",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "id"],
                "unique_together": {("project", "page_number")},
            },
        ),
    ]
