# Generated by Django 5.2.12 on 2026-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_projectimagepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="page_image_placement",
            field=models.CharField(default="none", max_length=16),
        ),
    ]
