# Generated by Django 5.2.13 on 2026-04-09 09:41

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_creditaccount_creditledgerentry_aiusagecharge"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIModelPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=64, unique=True)),
                (
                    "input_usd_per_1m",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                (
                    "output_usd_per_1m",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ai_parsed", "AI parsed"),
                            ("human_revised", "Human revised"),
                        ],
                        default="ai_parsed",
                        max_length=32,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_human_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
        migrations.AddField(
            model_name="aiusagecharge",
            name="request_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="project",
            name="total_cost_usd",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=12
            ),
        ),
    ]
