# Generated by Django 5.2.13 on 2026-04-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_openaimodelpricing_aiusagecharge_request_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimagestyle",
            name="discourage_text_in_images",
            field=models.BooleanField(default=False),
        ),
    ]
