# Generated by Django 5.2.13 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_projectimagestyle_discourage_text_in_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_generation_pivot_language",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
