# Generated by Django 5.2.13 on 2026-04-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_image_generation_pivot_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_generation_pivot_language",
        ),
    ]
