# Generated by Django 5.2.13 on 2026-04-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_remove_project_image_generation_pivot_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_generation_pivot_language",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
