# Generated by Django 5.2.13 on 2026-04-18 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_community_project_access_scope_project_community_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImagePageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_index", models.PositiveIntegerField()),
                ("image_model", models.CharField(default="gpt-image-1", max_length=64)),
                ("image_path", models.CharField(blank=True, max_length=512)),
                ("generation_prompt", models.TextField(blank=True)),
                ("image_revised_prompt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="projects.projectimagepage",
                    ),
                ),
            ],
            options={
                "ordering": ["page_id", "variant_index", "id"],
                "unique_together": {("page", "variant_index")},
            },
        ),
        migrations.AddField(
            model_name="projectimagepage",
            name="preferred_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="projects.projectimagepagevariant",
            ),
        ),
    ]
