# Generated by Django 4.2.13 on 2026-04-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_profile_dialogue_memory_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PictureDictionary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(blank=True, default="", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="picture_dictionary", to="projects.community"),
                ),
                (
                    "organiser",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="managed_picture_dictionaries", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="picture_dictionary", to="projects.project"),
                ),
            ],
            options={
                "ordering": ["community_id"],
            },
        ),
    ]
