# Generated by Django 4.2.13 on 2026-04-23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_picturedictionary"),
    ]

    operations = [
        migrations.CreateModel(
            name="PictureDictionaryEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("surface", models.CharField(max_length=255)),
                ("lemma", models.CharField(blank=True, default="", max_length=255)),
                ("pos", models.CharField(blank=True, default="", max_length=64)),
                ("image_path", models.CharField(blank=True, default="", max_length=512)),
                ("current_page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dictionary",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="projects.picturedictionary"),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [models.Index(fields=["dictionary", "is_active"], name="projects_pic_diction_d6b1e2_idx")],
            },
        ),
    ]
