# Generated by Django 5.2.13 on 2026-04-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_picturedictionaryentry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="picturedictionaryentry",
            new_name="picdictentry_dict_active_idx",
            old_name="projects_pic_diction_d6b1e2_idx",
        ),
    ]
