# Generated by Django 5.2.14 on 2026-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_issueupdatesuggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseset",
            name="flashcard_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("form_to_meaning", "Form → meaning"),
                    ("meaning_to_form", "Meaning → form"),
                    ("image_to_form", "Image → form"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
