# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_alter_exerciseset_flashcard_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="audio_mode",
            field=models.CharField(
                choices=[
                    ("tts", "Use TTS audio"),
                    ("none", "No audio / skip TTS"),
                ],
                default="tts",
                max_length=16,
            ),
        ),
    ]
