# Generated by Codex on 2026-06-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_profile_byok_fields"),
        ("projects", "0038_projectimagestyle_disallow_text_in_images"),
    ]

    operations = []
