# Generated by Django 5.2.14 on 2026-06-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0039_merge_0036_profile_byok_fields_0038_projectimagestyle_disallow_text_in_images",
        ),
        (
            "projects",
            "0039_merge_20260524_1408",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("usage", "Usage charge"),
                    ("admin_adjust", "Admin adjustment"),
                    ("transfer_out", "Transfer sent"),
                    ("transfer_in", "Transfer received"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="flashcard_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("form_to_meaning", "Form → meaning"),
                    ("meaning_to_form", "Meaning → form"),
                    ("image_to_form", "Image → form"),
                    ("form_to_image", "Form → image"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
