# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_alter_creditledgerentry_entry_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseset",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("cloze", "Cloze"),
                    ("flashcard", "Flashcard"),
                    ("word_scramble", "Word scramble"),
                ],
                default="cloze",
                max_length=32,
            ),
        ),
    ]
