# Generated by Django 5.2.16 on 2026-07-30 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_alter_exerciseset_exercise_type_crossword"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyProjectImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system", models.CharField(max_length=64)),
                ("legacy_project_id", models.CharField(max_length=128)),
                (
                    "library_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "bundle_relative_path",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "source_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "original_owner_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("importing", "Importing"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_project_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_import_records",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["source_system", "legacy_project_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_system", "legacy_project_id"),
                        name="unique_legacy_project_source_identity",
                    )
                ],
            },
        ),
    ]
